[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
build_flags = 
    -D LOG_INFO_ENABLE
    -D LOG_WARN_ENABLE
    -D LOG_ERROR_ENABLE
    -D LOG_DEBUG_ENABLE
    -D LOG_VERBOSE_ENABLE